In [0]:
import numpy as np
from numpy import genfromtxt

In [0]:
data = genfromtxt('/content/bank_note_data.txt', delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:, 4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:, 0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [0]:
X = features
y = labels

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [0]:
scaler = MinMaxScaler()

In [13]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [0]:
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [0]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [19]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
 - 2s - loss: 0.6803 - accuracy: 0.5778
Epoch 2/50
 - 0s - loss: 0.6703 - accuracy: 0.5800
Epoch 3/50
 - 0s - loss: 0.6573 - accuracy: 0.6279
Epoch 4/50
 - 0s - loss: 0.6397 - accuracy: 0.6834
Epoch 5/50
 - 0s - loss: 0.6232 - accuracy: 0.6931
Epoch 6/50
 - 0s - loss: 0.6050 - accuracy: 0.7312
Epoch 7/50
 - 0s - loss: 0.5873 - accuracy: 0.7573
Epoch 8/50
 - 0s - loss: 0.5705 - accuracy: 0.7617
Epoch 9/50
 - 0s - loss: 0.5547 - accuracy: 0.7639
Epoch 10/50
 - 0s - loss: 0.5378 - accuracy: 0.7748
Epoch 11/50
 - 0s - loss: 0.5195 - accuracy: 0.7813
Epoch 12/50
 - 0s - loss: 0.5021 - accuracy: 0.7943
Epoch 13/50
 - 0s - loss: 0.4871 - accuracy: 0.8085
Epoch 14/50
 - 0s - loss: 0.4722 - accuracy: 0.8183
Epoch 15/50
 - 0s - loss: 0.4585 - accuracy: 0.8248
Epoch 16/50
 - 0s - loss: 0.4448 - accuracy: 0.8346
Epoch 17/50
 - 0s - loss: 0.4320 - accuracy: 0.8422
Epoch 18/50
 - 0s - loss: 0.4201 - accuracy: 0.8487
Epoch 19/50
 - 0s - loss: 0.4089 - accuracy: 0.8487
Epoch 20/50
 - 0s - l

In [0]:
from sklearn.metrics import confusion_matrix, classification_report

In [0]:
predictions = model.predict_classes(scaled_X_test)

In [23]:
confusion_matrix(y_test, predictions)

array([[247,  10],
       [ 12, 184]])

In [25]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.95      0.96      0.96       257
         1.0       0.95      0.94      0.94       196

    accuracy                           0.95       453
   macro avg       0.95      0.95      0.95       453
weighted avg       0.95      0.95      0.95       453



In [0]:
model.save('forgery_model.h5')

In [0]:
from keras.models import load_model

In [0]:
newmodel = load_model('forgery_model.h5')

In [29]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    