In [35]:
import numpy as np
from sklearn.datasets import load_iris

In [36]:
iris = load_iris()

In [41]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [42]:
X = iris.data

In [43]:
y = iris.target

In [44]:
from keras.utils import to_categorical

In [45]:
y = to_categorical(y)

In [46]:
y.shape

(150, 3)

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [49]:
from sklearn.preprocessing import MinMaxScaler

In [50]:
scaler = MinMaxScaler()

In [51]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [52]:
scaled_X_train = scaler.transform(X_train)

In [53]:
scaled_X_test = scaler.transform(X_test)

In [54]:
from keras.models import Sequential
from keras.layers import Dense

In [56]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [57]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [59]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 0.6633 - accuracy: 0.6600
Epoch 2/150
 - 0s - loss: 0.6614 - accuracy: 0.6600
Epoch 3/150
 - 0s - loss: 0.6596 - accuracy: 0.6600
Epoch 4/150
 - 0s - loss: 0.6578 - accuracy: 0.6600
Epoch 5/150
 - 0s - loss: 0.6561 - accuracy: 0.6600
Epoch 6/150
 - 0s - loss: 0.6543 - accuracy: 0.6600
Epoch 7/150
 - 0s - loss: 0.6524 - accuracy: 0.6600
Epoch 8/150
 - 0s - loss: 0.6509 - accuracy: 0.6600
Epoch 9/150
 - 0s - loss: 0.6491 - accuracy: 0.6600
Epoch 10/150
 - 0s - loss: 0.6475 - accuracy: 0.6600
Epoch 11/150
 - 0s - loss: 0.6459 - accuracy: 0.6600
Epoch 12/150
 - 0s - loss: 0.6442 - accuracy: 0.6600
Epoch 13/150
 - 0s - loss: 0.6427 - accuracy: 0.6600
Epoch 14/150
 - 0s - loss: 0.6411 - accuracy: 0.6600
Epoch 15/150
 - 0s - loss: 0.6394 - accuracy: 0.6600
Epoch 16/150
 - 0s - loss: 0.6377 - accuracy: 0.6600
Epoch 17/150
 - 0s - loss: 0.6360 - accuracy: 0.6600
Epoch 18/150
 - 0s - loss: 0.6342 - accuracy: 0.6600
Epoch 19/150
 - 0s - loss: 0.6324 - accuracy: 0.6600
Ep

In [60]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [61]:
predictions = model.predict_classes(scaled_X_test)

In [62]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [65]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [67]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  3, 13]])

In [68]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.82      0.93      0.87        15
           2       0.93      0.81      0.87        16

    accuracy                           0.92        50
   macro avg       0.92      0.92      0.91        50
weighted avg       0.92      0.92      0.92        50



In [69]:
print(accuracy_score(y_test.argmax(axis=1), predictions))

0.92
